#!/usr/bin/env sh
rootdir=$(dirname `dirname $0`)
srcdir=$rootdir/src
mkdir -p $srcdir

# create site
# set lang
docker run --rm -v $srcdir:/docs -u `id -u`:`id -g` ghcr.io/kfjt/mkdocsjp:latest new .
docker run --rm -v $srcdir:/docs -u `id -u`:`id -g` --entrypoint python3 ghcr.io/kfjt/mkdocsjp:latest /opt/set_lang.py
