# ghcr.io/<GitHubアカウント>/<image名>:<タグ>のimageをGitHub Packagesにpushするworkflow
# vから始まるtag(例:`v1.2.3`)のpushでjobsを実行する
name: Docker Build and Push
on:
  push:
    tags:
      - v*
jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | sed -e 's,^[^/]*/,,')
          IMAGE_ID=$(echo "ghcr.io/$GITHUB_ACTOR/$REPO_NAME" | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' -e 's/^v//')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker build --build-arg VERSION=$VERSION --tag $IMAGE_ID:latest --tag $IMAGE_ID:$VERSION .
      - name: Push Docker Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | sed -e 's,^[^/]*/,,')
          IMAGE_ID=$(echo "ghcr.io/$GITHUB_ACTOR/$REPO_NAME" | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' -e 's/^v//')
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION